# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : "https://lifelonginvestor.net" # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : '/' # does not include hostname
title   : Lifelong Investor LLC
description: > # this means to ignore newlines until "Language & timezone"
  Lifelong Investor LLC | 终身投资者有限责任公司

## => Language and Timezone
##############################
lang: en # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: America/New_York # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : organization # "person" (default), "organization"
  name      : Lifelong Investor LLC
  url       : /about.html
  avatar    : /assets/investor-avatar.png
  bio       : Meet a group of like-minded friends who are willing to walk hand in hand on the road of lifelong investment. 邂逅一群志同道合的朋友，愿意在终身投资之路上携手同行。
  email     : lifelonginvestorllc@gmail.com
  facebook  : # lifelonginvestorllc # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # lifelonginvestorllc # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # lifelonginvestorllc # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name/
  github    : # lifelonginvestorllc # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: lifelonginvestorllc/lifelonginvestorllc.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: gitalk # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: LifelongInvestor # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
#  gitalk:
#    clientID    : 4795af18f9129677a7ce # GitHub Application Client ID
#    clientSecret: cb054b9f817765c9b30928594cbd624b7f7734bf # GitHub Application Client Secret
#    repository  : lifelonginvestorllc.comments # GitHub public repository for comments purpose
#    owner       : lifelonginvestorllc # GitHub repo owner
#    admin: [lifelonginvestorllc, tochenliqun] # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
#    distractionFreeMode: true

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: "default" # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: 58222695cf2d5e5d8 # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : UA-109230910-1 # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /test
  - /vendor

collections:
  pages:
    output: true
  coding:
    output: true
  algorithm:
    output: true
  architect:
    output: true
  programmer:
    output: true             
  blogger:
    output: true
  investor:
    output: true
    
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      show_date: false
      pageview: true
  - scope:
      path: ""
      type: articles
    values:
      show_date: false      
  - scope:
      path: ""
      type: articles2
    values:
      show_date: false
  - scope:
      path: "_investor"
    values:
      layout: article
      cover: /assets/images/investor/investor.png
      categories: [Investor]
      sharing: true
      aside:
        toc: true
      show_date: false
      pageview: true                  
      
## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji